<a href="https://colab.research.google.com/github/SMahesh90/Machine-Learning/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Perform arithmetic operations on NumPy arrays.

In [1]:
import numpy as np

#array using numpy
a = np.array([1,2,3])

print("Addition: ", a+5) #adding 5 to array
print("Subtraction: ",5-a) #subtracting 5 from array
print("Division: ",5/a) #dividing 5 from array
print("Multiplication: ",5*a) #Multiplying 5 to array


Addition:  [6 7 8]
Subtraction:  [4 3 2]
Division:  [5.         2.5        1.66666667]
Multiplication:  [ 5 10 15]


2)Write a script to compute the mean and standard deviation of a NumPy array.

In [2]:
m = np.mean(a) #mean
print("Mean: ",m)

sd = np.std(a) #standard deviation
print("Standard deviation: ",sd)

Mean:  2.0
Standard deviation:  0.816496580927726


3) Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [7]:
x = np.arange(10,50,5) #printing the number from 10 to 50 with step size of 5
print(x)

[10 15 20 25 30 35 40 45]


4) Reshape the array into a 2x4 matrix.

In [8]:
b = np.reshape(x,(2,4)) # reshaping the array to 2x4 array from x array
print(b)

[[10 15 20 25]
 [30 35 40 45]]


5)  Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

    • Extract the sub-matrix containing the last two rows and first two columns.
    • Replace all elements greater than 4 with 0.


In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

y = arr[1:,:2]
print("Original array: ",y) # array with last two rows and first two columns
y[y > 4] = 0
print("after replacing elements greater 4 with 0: ", y) #array with greater 4 repalcing with zeroes.

Original array:  [[4 5]
 [7 8]]
after replacing:  [[4 0]
 [0 0]]


6)  Create two 1D arrays:

• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

• Perform element-wise addition, multiplication, and division.

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("addition: ", a+b) #adding the two arrays
print("Division: ",a/b) #dividing the two arrays
print("Multipliaction: ",a*b) #multiplying the two arrays

addition:  [5 7 9]
Division:  [0.25 0.4  0.5 ]
Multipliaction:  [ 4 10 18]


7) Create a random NumPy array of size (4, 4). Compute:

• Mean of each column.

• Maximum value of the entire array.

• Sum of all elements.

In [23]:
arr = np.random.random((4,4))
print("Original array: ",arr) # prints the random values in 4x4 form

mean = np.mean(arr)
m = np.max(arr)
s = np.sum(arr)
print("mean:",mean) #prints the mean values
print("Maximum value: ",m) #prints the maximum value
print("Sum of values: ",s) #prints the sum of values

Original array:  [[0.88757217 0.91205563 0.45450325 0.01669985]
 [0.32368269 0.66557646 0.35037102 0.07324361]
 [0.88725485 0.77603219 0.16334924 0.46046205]
 [0.57752698 0.39500336 0.86790004 0.80959838]]
mean: 0.538801985826765
Maximum value:  0.9120556327831907
Sum of values:  8.62083177322824


8) Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [25]:
arr = np.array([1,2,3,4])

res = arr+10  #adding 10 to elements

res = res*2   #multiplying the elements with 2
print(res)

[22 24 26 28]


9) Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:

• Extract the second "layer" (i.e., the second 2D array) in the first dimension.

• Extract the first two rows and the last three columns from each "layer."

• Replace all elements divisible by 3 with -1.

In [34]:
arr = np.random.randint(1,100,(3,4,5))

print(" the second 2D array: ",arr[1]) #Extracting the second "layer"
print("-----------------------------------")

# Extract the first two rows and the last three columns from each "layer."
print(arr[:,:2,-3:])

print("-----------------------------------")
arr[arr%3 == 0] = -1

print("all elements divisible by 3 replacing with -1: ", arr)

 the second 2D array:  [[56  7 56 45 78]
 [18 80 46 23 96]
 [17 45  5 23 71]
 [31 79 23 20 44]]
-----------------------------------
[[[90 10 49]
  [36 14 82]]

 [[56 45 78]
  [46 23 96]]

 [[98 94 22]
  [35 88 51]]]
-----------------------------------
all elements divisible by 3 replacing with -1:  [[[65 19 -1 10 49]
  [-1 68 -1 14 82]
  [-1 -1 59 95 20]
  [20 86 37 71 52]]

 [[56  7 56 -1 -1]
  [-1 80 46 23 -1]
  [17 -1  5 23 71]
  [31 79 23 20 44]]

 [[94 55 98 94 22]
  [-1 13 35 88 -1]
  [-1 79 52 -1 -1]
  [65 -1  8 -1 46]]]


10)   Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:

• Subtract the mean of each row from its respective elements (row-wise
normalization).

• Create a new array by squaring all the elements in arr.

• Find the indices of the top 3 maximum values in the entire array.

In [28]:
arr = np.random.randint(1,20,(3,3))
print(arr)

newArr = np.square(arr)# squaring the array
print(newArr)

# subtracting the mean of each row from its respective elements (row-wise normalization)
arr = arr - arr.mean(axis=1, keepdims=True)

sortArr = np.sort(arr.flatten())# top 3 maximum values
print(sortArr[-3:])

[[ 9 17  3]
 [10  5  5]
 [13  5 18]]
[[ 81 289   9]
 [100  25  25]
 [169  25 324]]
[3.33333333 6.         7.33333333]
